[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "echoquality"
version = "0.1.0"
description = "A Two-Stage Pattern Recognition Framework for Echocardiographic Image Quality Assessment and Adaptive Image Processing"
readme = "README.md"
requires-python = ">=3.10"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]